topics = {
"1":
{
"1": "painting",
"2": "cinema",
"3": "history",
"4": "world war II",
"5": "chemistry",
"6": "physics",
"7": "music",
"8": "literature",
"9": "mathematics",
"10": "biology",
"11": "architecture",
"12": "photography",
"13": "astronomy",
"14": "geography",
"15": "psychology",
"16": "fashion",
"17": "cooking",
"18": "technology",
"19": "environment",
"20": "medicine",
"21": "sports",
"22": "computer science",
"23": "economics",
"24": "politics",
"25": "philosophy",
"26": "sociology",
"27": "education",
"28": "language",
"29": "anthropology",
"30": "law",
"31": "religion",
"32": "marketing",
"33": "automotive",
"34": "business",
"35": "crime",
"36": "engineering",
"37": "health",
"38": "culture",
"39": "fitness",
"40": "gaming",
"41": "animals",
"42": "climate change",
"43": "artificial intelligence",
"44": "military",
"45": "social media",
"46": "space",
"47": "advertising",
"48": "human rights",
"49": "travelling",
"50": "architecture",
"51": "finance",
"52": "robotics",
"53": "pop culture",
"54": "performing arts",
"55": "paleontology",
"56": "archeology",
"57": "maritime",
"58": "nutrition",
"59": "wildlife conservation",
"60": "pandemics",
"61": "genetics",
"62": "psychiatry",
"63": "oceanography",
"64": "farming",
"65": "forensics",
"66": "diving",
"67": "visualization",
"68": "biochemistry",
"69": "nanotechnology",
"70": "epidemiology",
"71": "forestry",
"72": "aviation",
"73": "animation",
"74": "culinary arts",
"75": "sexual orientation",
"76": "mountaineering",
"77": "geology",
"78": "biotechnology",
"79": "futurism",
"80": "linguistics",
"81": "television",
"82": "mythology",
"83": "journalism",
"84": "graphic design",
"85": "applied physics",
"86": "cryptozoology",
"87": "immigration",
"88": "public relations",
"89": "swimming",
"90": "biomechanics",
"91": "startup",
"92": "banking",
"93": "cryptography",
"94": "machine learning",
"95": "forensic science",
"96": "logistics",
"97": "patents",
"98": "biodiversity",
"99": "fixtures",
"100": "concerts"
},
"2":
{
 "1":"Science",
 "2":"Technology",
 "3":"Physics",
 "4":"Chemistry",
 "5":"Biology",
 "6":"Astronomy",
 "7":"Computer Science",
 "8":"Mathematics",
 "9":"Nanotechnology",
 "10":"Genetics",
 "11":"Environmental Science",
 "12":"Geology",
 "13":"Engineering",
 "14":"Robotics",
 "15":"Artificial Intelligence",
 "16":"Cryptography",
 "17":"Renewable Energy",
 "18":"Materials Science",
 "19":"Neuroscience",
 "20":"Astrophysics",
 "21":"Biotechnology",
 "22":"Quantum Computing",
 "23":"Microbiology",
 "24":"Earth Science",
 "25":"Data Science",
 "26":"Electricity",
 "27":"Superconductivity",
 "28":"Chemical Engineering",
 "29":"Space Exploration",
 "30":"Telecommunication",
 "31":"Cybersecurity",
 "32":"Robotics",
 "33":"Nuclear Physics",
 "34":"Molecular Biology",
 "35":"Signal Processing",
 "36":"Biochemistry",
 "37":"Meteorology",
 "38":"Software Engineering",
 "39":"Genetic Engineering",
 "40":"Civil Engineering",
 "41":"Magnetic Resonance Imaging",
 "42":"Nanomedicine",
 "43":"Optics",
 "44":"Animal Behavior",
 "45":"Information Theory",
 "46":"Agricultural Science",
 "47":"Linear Algebra",
 "48":"Cell Biology",
 "49":"Atomic Physics",
 "50":"Energy Storage",
 "51":"Cloud Computing",
 "52":"Biomechanics",
 "53":"Sociology of Technology",
 "54":"Marine Biology",
 "55":"Technology Transfer",
 "56":"Calculus",
 "57":"Computational Neuroscience",
 "58":"Epidemiology",
 "59":"Privacy-enhancing Technologies",
 "60":"Pharmacology",
 "61":"Wireless Networks",
 "62":"Psychology of Technology",
 "63":"Genomics",
 "64":"Civil Engineering",
 "65":"Artificial Neural Networks",
 "66":"Ecology",
 "67":"Software Development",
 "68":"Smart Grid",
 "69":"Physical Chemistry",
 "70":"Forensic Science",
 "71":"Transportation Engineering",
 "72":"Nanoengineering",
 "73":"Histology",
 "74":"Cosmology",
 "75":"Network Security",
 "76":"Radio Astronomy",
 "77":"Biological Engineering",
 "78":"Crystallography",
 "79":"Biomedical Engineering",
 "80":"Environmental Engineering",
 "81":"Virology",
 "82":"Genomic Medicine",
 "83":"Immunology",
 "84":"Marine Engineering",
 "85":"Biosensors",
 "86":"Mechatronics",
 "87":"Global Positioning System",
 "88":"Structural Engineering",
 "89":"Fluorescence Microscopy",
 "90":"Renewable Resource Management",
 "91":"Light-emitting Diodes",
 "92":"Volcanology",
 "93":"Surface Science",
 "94":"Systems Biology",
 "95":"Geophysics",
 "96":"Object-oriented Programming",
 "97":"Industrial Engineering",
 "98":"Cognitive Science",
 "99": "Statistics",
 "100":"Machine Learning",
 },
 "3":{
  "1": "Cinema of the United States",
  "2": "French New Wave",
  "3": "Italian neorealism",
  "4": "German Expressionism",
  "5": "Japanese New Wave",
  "6": "Surrealism",
  "7": "Film noir",
  "8": "Documentary film",
  "9": "Film theory",
  "10": "Animation",
  "11": "Silent film",
  "12": "Historical period drama",
  "13": "French cinema",
  "14": "Mexican cinema",
  "15": "British cinema",
  "16": "Russian cinema",
  "17": "Indian cinema",
  "18": "Chinese cinema",
  "19": "Film editing",
  "20": "Screenwriting",
  "21": "Acting",
  "22": "Film producer",
  "23": "Film director",
  "24": "Comedy film",
  "25": "Horror film",
  "26": "Musical film",
  "27": "War film",
  "28": "Science fiction film",
  "29": "Fantasy film",
  "30": "Art film",
  "31": "Romantic comedy film",
  "32": "Literature",
  "33": "Novel",
  "34": "Poetry",
  "35": "Drama",
  "36": "Essay",
  "37": "Historical fiction",
  "38": "Biography",
  "39": "Autobiography",
  "40": "Science fiction literature",
  "41": "Fantasy literature",
  "42": "Satire",
  "43": "Mystery fiction",
  "44": "Romance novel",
  "45": "Crime fiction",
  "46": "Short story",
  "47": "Horror fiction",
  "48": "Historical literature",
  "49": "Art history",
  "50": "Painting",
  "51": "Sculpture",
  "52": "Architecture",
  "53": "Photography",
  "54": "Filmography",
  "55": "History of cinema",
  "56": "Postmodern literature",
  "57": "New Media Art",
  "58": "Contemporary art",
  "59": "Ballet",
  "60": "Opera",
  "61": "Tragedy",
  "62": "Philosophy of art",
  "63": "Pop art",
  "64": "Dada",
  "65": "Neo-Dada",
  "66": "Abstract expressionism",
  "67": "Impressionism",
  "68": "Cubism",
  "69": "Minimalism",
  "70": "Visual arts",
  "71": "Belles-lettres",
  "72": "Postcolonial literature",
  "73": "Classic literature",
  "74": "Conceptual art",
  "75": "Avant-garde",
  "76": "Symbolism",
  "77": "Romanticism",
  "78": "Realism",
  "79": "Expressionism",
  "80": "Naturalism",
  "81": "Performing arts",
  "82": "Grammy Awards",
  "83": "Tony Awards",
  "84": "Oscar Awards",
  "85": "Emmy Awards",
  "86": "Golden Globe Awards",
  "87": "Academy Award for Best Picture",
  "88": "Hollywood Walk of Fame",
  "89": "Broadway theatre",
  "90": "Modern art",
  "91": "Installation art",
  "92": "Printmaking",
  "93": "Photorealism",
  "94": "Modernist literature",
  "95": "Existentialism",
  "96": "historical drama",
  "97": "Abstract photography",
  "98": "Avant-garde film",
  "99": "German cinema",
  "100": "Neoclassicism"
},
"4":
{
  "1": "Barack Obama",
  "2": "Leonardo da Vinci",
  "3": "Albert Einstein",
  "4": "Marylin Monroe",
  "5": "Michael Jordan",
  "6": "Marie Curie",
  "7": "William Shakespeare",
  "8": "Vincent van Gogh",
  "9": "Amelia Earhart",
  "10": "Steve Jobs",
  "11": "Sigmund Freud",
  "12": "Oprah Winfrey",
  "13": "Pablo Picasso",
  "14": "Martin Luther King Jr.",
  "15": "Wolfgang Amadeus Mozart",
  "16": "Madonna",
  "17": "Isaac Newton",
  "18": "Anne Frank",
  "19": "Jane Austen",
  "20": "Nelson Mandela",
  "21": "J.K. Rowling",
  "22": "Frida Kahlo",
  "23": "Winston Churchill",
  "24": "Elvis Presley",
  "25": "Mark Twain",
  "26": "Kurt Cobain",
  "27": "Leon Trotsky",
  "28": "Marlon Brando",
  "29": "Coco Chanel",
  "30": "Andy Warhol",
  "31": "Frida Kahlo",
  "32": "Frank Sinatra",
  "33": "Virginia Woolf",
  "34": "Fidel Castro",
  "35": "Leonardo DiCaprio",
  "36": "Grace Kelly",
  "37": "Pele",
  "38": "Simon Bolivar",
  "39": "Bob Dylan",
  "40": "Che Guevara",
  "41": "Vincent Price",
  "42": "Chester Bennington",
  "43": "Marie Antoinette",
  "44": "George Michael",
  "45": "Julia Child",
  "46": "Salvador Dali",
  "47": "James Dean",
  "48": "Jimi Hendrix",
  "49": "Socrates",
  "50": "Mahatma Gandhi",
  "51": "Queen Victoria",
  "52": "Alexander Graham Bell",
  "53": "Thomas Edison",
  "54": "Stan Lee",
  "55": "Vladimir Lenin",
  "56": "Audrey Hepburn",
  "57": "Barbara Walters",
  "58": "Muhammad Ali",
  "59": "Anne Hathaway",
  "60": "Louis Armstrong",
  "61": "Lucille Ball",
  "62": "Queen Elizabeth II",
  "63": "Igor Stravinsky",
  "64": "Pope Francis",
  "65": "Marilyn Manson",
  "66": "Diana, Princess of Wales",
  "67": "Albert Schweitzer",
  "68": "Ivan Pavlov",
  "69": "Julius Caesar",
  "70": "Helen Keller",
  "71": "Rembrandt",
  "72": "Georges Méliès",
  "73": "Freddie Mercury",
  "74": "Ralph Lauren",
  "75": "John F. Kennedy",
  "76": "Steve Irwin",
  "77": "Ingrid Bergman",
  "78": "Ada Lovelace",
  "79": "Malala Yousafzai",
  "80": "Ludwig van Beethoven",
  "81": "Samuel L. Jackson",
  "82": "Tomioka Tessai",
  "83": "Noam Chomsky",
  "84": "Pierce Brosnan",
  "85": "Ernest Hemingway",
  "86": "Charles Darwin",
  "87": "Mother Teresa",
  "88": "Benjamin Franklin",
  "89": "P.T. Barnum",
  "90": "George Washington",
  "91": "Bill Gates",
  "92": "Angela Merkel",
  "93": "William Wallace",
  "94": "Stephen King",
  "95": "Hillary Clinton",
  "96": "Rosa Parks",
  "97": "Sun Yat-sen",
  "98": "Napoleon Bonaparte",
  "99": "Haruki Murakami",
  "100": "John Lennon",
},
"5":
{
  "1": "Ancient Egypt",
  "2": "Roman Empire",
  "3": "French Revolution",
  "4": "American Civil War",
  "5": "World War I",
  "6": "World War II",
  "7": "Cold War",
  "8": "Holocaust",
  "9": "Industrial Revolution",
  "10": "French Colonial Empire",
  "11": "Russian Revolution",
  "12": "Great Depression",
  "13": "Mayan civilization",
  "14": "Inca Empire",
  "15": "Greek mythology",
  "16": "Ming dynasty",
  "17": "Vikings",
  "18": "Renaissance",
  "19": "Aztec Empire",
  "20": "Hinduism",
  "21": "Buddhism",
  "22": "Islam",
  "23": "Christianity",
  "24": "Plague of Justinian",
  "25": "Black Death",
  "26": "Age of Exploration",
  "27": "French colonization of the Americas",
  "28": "American Revolution",
  "29": "Gutenberg printing press",
  "30": "Reformation",
  "31": "English Civil War",
  "32": "Apartheid",
  "33": "Vietnam War",
  "34": "Holodomor",
  "35": "Australian Aboriginal Dreamtime",
  "36": "Māori people",
  "37": "Beijing Olympic Games 2008",
  "38": "Treaty of Versailles",
  "39": "Berlin Wall",
  "40": "Russian Civil War",
  "41": "Ancient Greece",
  "42": "Mongol Empire",
  "43": "Battle of Waterloo",
  "44": "Haitian Revolution",
  "45": "Cuban Missile Crisis",
  "46": "Salem Witch Trials",
  "47": "Indian Rebellion of 1857",
  "48": "Pearl Harbor",
  "49": "Hundred Years' War",
  "50": "Opium Wars",
  "51": "Apartheid in South Africa",
  "52": "Iran Hostage Crisis",
  "53": "Harlem Renaissance",
  "54": "Space Race",
  "55": "Mexican Revolution",
  "56": "Pompeii and Herculaneum",
  "57": "Soviet-Afghan War",
  "58": "War of 1812",
  "59": "Russian Empire",
  "60": "Great Irish Famine",
  "61": "Battle of Stalingrad",
  "62": "Ancient Rome",
  "63": "Crusades",
  "64": "Spanish Inquisition",
  "65": "First Opium War",
  "66": "Manhattan Project",
  "67": "Assassination of Abraham Lincoln",
  "68": "Mexican-American War",
  "69": "Boxer Rebellion",
  "70": "Hurricane Katrina",
  "71": "Magna Carta",
  "72": "American Revolutionary War",
  "73": "Trail of Tears",
  "74": "Lord of the Rings",
  "75": "Apollo Moon Landing",
  "76": "Prohibition",
  "77": "Battle of Hastings",
  "78": "Fall of the Berlin Wall",
  "79": "Iran-Iraq War",
  "80": "Napoleonic Wars",
  "81": "Shot Heard 'Round the World",
  "82": "American Westward Expansion",
  "83": "Sinking of the Titanic",
  "84": "Chernobyl disaster",
  "85": "Five-Year Plans (Soviet Union)",
  "86": "Yom Kippur War",
  "87": "Yugoslav Wars",
  "88": "Arab Spring",
  "89": "End of apartheid in South Africa",
  "90": "Tiananmen Square protests",
  "91": "Romanesque architecture",
  "92": "Byzantine Empire",
  "93": "Punic Wars",
  "94": "Ancient China",
  "95": "American Indian Wars",
  "96": "Harry Potter",
  "97": "Teacher's long march",
  "98": "Uruguay Round",
  "99": "First Crusade",
  "100": "Gulf War"
},"6":
{
  "1": "Technology in Education",
  "2": "Climate Change",
  "3": "Space Exploration",
  "4": "Artificial Intelligence",
  "5": "Social Media and its Impact",
  "6": "Sustainable Living",
  "7": "Cybersecurity",
  "8": "Movies",
  "9": "Renewable Energy",
  "10": "Virtual Reality",
  "11": "Data Privacy",
  "12": "Celebrities",
  "13": "Immigration",
  "14": "World War II",
  "15": "Politics",
  "16": "Mathematics",
  "17": "Chemistry",
  "18": "Internet of Things",
  "19": "Mental Health Awareness",
  "20": "Robotics",
  "21": "Cultural Diversity and Inclusion",
  "22": "Driverless Cars",
  "23": "E-commerce and Online Shopping Trends",
  "24": "The Impact of Social Networking on Relationships",
  "25": "Poems",
  "26": "Space Travel and Tourism",
  "27": "Medicine",
  "28": "Soccer",
  "29": "Basketball",
  "30": "Disasters",
  "31": "historical events",
  "32": "historical places",
  "33": "Nanotechnology",
  "34": "Privacy and Security in the Digital Age",
  "35": "Augmented Reality",
  "36": "Economic Growth and Development",
  "37": "Future of Transportation",
  "38": "Censorship and Freedom of Speech",
  "39": "eSports and Competitive Gaming",
  "40": "The Role of Artificial Intelligence in Healthcare",
  "41": "Renewable Energy Policies and Challenges",
  "42": "Social Impact of Mobile Technology",
  "43": "Ageing Population and Senior Care",
  "44": "Remote Work and Digital Nomadism",
  "45": "3D Printing",
  "46": "Music Streaming and its Effect on the Music Industry",
  "47": "Blockchain and Supply Chain Management",
  "48": "Climate-Resilient Agriculture",
  "49": "Implications of Quantum Computing",
  "50": "Importance of Digital Literacy",
  "51": "Disaster Response Technologies",
  "52": "Online Privacy Regulation",
  "53": "Genetic Testing and Privacy Concerns",
  "54": "Smart Cities and Urban Development",
  "55": "Virtual Assistants and Smart Home Technology",
  "56": "Green Buildings and Sustainable Architecture",
  "57": "Impact of Automation on Job Satisfaction",
  "58": "Effects of Air Pollution on Human Health",
  "59": "Cloud Computing and Data Storage",
  "60": "Dependence on Technology",
  "61": "Gender Equality in STEM Fields",
  "62": "Brain-Computer Interfaces",
  "63": "Benefits and Risks of Nanomaterials",
  "64": "Social Media Influencers and Marketing",
  "65": "Global Water Crisis",
  "66": "Challenges of Space Colonization",
  "67": "Digital Divide and Access to Technology",
  "68": "Data Science and Analytics",
  "69": "Artificial Intelligence in Finance",
  "70": "The Big Bang Theory and the Origin of the Universe",
  "71": "Government Surveillance and Privacy Rights",
  "72": "The Role of Technology in Agriculture",
  "73": "Juvenile Cyberbullying",
  "74": "E-waste and Recycling Electronics",
  "75": "Digital Currency Adoption and Challenges",
  "76": "Ethics of Gene Editing",
  "77": "Effects of Social Media on Mental Health",
  "78": "Development of Smart Fabrics",
  "79": "Augmented Reality in Sports",
  "80": "Effects of Texting on Language Proficiency",
  "81": "Role of Technology in Disaster Management",
  "82": "The Future of Print Media",
  "83": "Virtual Museums and Cultural Preservation",
  "84": "Application of AI in Marketing",
  "85": "Algorithms and Bias",
  "86": "Future of Online Retail",
  "87": "Pros and Cons of Genetic Engineering in Food",
  "88": "Impact of Smartphones on Social Interactions",
  "89": "Bio-inspired Innovation",
  "90": "Digital Gambling and iGaming Trends",
  "91": "Risks and Benefits of Autonomous Weapons Systems",
  "92": "Online Voting and Election Security",
  "93": "AI in the Film and Entertainment Industry",
  "94": "Brain-Machine Interfaces for Rehabilitation",
  "95": "Role of Technology in Journalism",
  "96": "Holistic Approaches to Cybersecurity",
  "97": "Impacts of Mobile Payments on Traditional Banking",
  "98": "Cultural Impact of Streaming Services on Music",
  "99": "Telemedicine and Remote Patient Monitoring",
  "100": "Challenges of Quantum Cryptography"
},"7":
{
      "1": "Tokyo",
      "2": "New York",
      "3": "London",
      "4": "Paris",
      "5": "Beijing",
      "6": "Moscow",
      "7": "Rio de Janeiro",
      "8": "Sydney",
      "9": "Cairo",
      "10": "Bangkok",
      "11": "Berlin",
      "12": "Rome",
      "13": "Toronto",
      "14": "Athens",
      "15": "Mumbai",
      "16": "Madrid",
      "17": "Dublin",
      "18": "Seoul",
      "19": "Amsterdam",
      "20": "Venice",
      "21": "Vienna",
      "22": "Cape Town",
      "23": "Barcelona",
      "24": "Lucerne",
      "25": "Prague",
      "26": "Helsinki",
      "27": "Singapore",
      "28": "Rio de Janeiro",
      "29": "Havana",
      "30": "Budapest",
      "31": "Oslo",
      "32": "Montreal",
      "33": "Stockholm",
      "34": "Kuala Lumpur",
      "35": "Edinburgh",
      "36": "Buenos Aires",
      "37": "Vancouver",
      "38": "Sao Paulo",
      "39": "Marrakech",
      "40": "Chicago",
      "41": "Quebec City",
      "42": "Dubai",
      "43": "Copenhagen",
      "44": "Melbourne",
      "45": "Auckland",
      "46": "Istanbul",
      "47": "Florence",
      "48": "San Francisco",
      "49": "Zurich",
      "50": "Lisbon",
      "51": "Krakow",
      "52": "Brussels",
      "53": "Bristol",
      "54": "Wroclaw",
      "55": "Mexico City",
      "56": "Nairobi",
      "57": "Glasgow",
      "58": "Alicante",
      "59": "Sydney",
      "60": "Seville",
      "61": "Guangzhou",
      "62": "Los Angeles",
      "63": "Ottawa",
      "64": "Toronto",
      "65": "Phuket",
      "66": "Shanghai",
      "67": "Washington, D.C.",
      "68": "Manila",
      "69": "Ho Chi Minh City",
      "70": "Phnom Penh",
      "71": "Buenos Aires",
      "72": "Santiago",
      "73": "Edmonton",
      "74": "Rio de Janeiro",
      "75": "Blantyre",
      "76": "Wellington",
      "77": "Yerevan",
      "78": "Lima",
      "79": "Kingston",
      "80": "Denver",
      "81": "Vientiane",
      "82": "Jaipur",
      "83": "Caracas",
      "84": "Riyadh",
      "85": "Muscat",
      "86": "Male",
      "87": "Honolulu",
      "88": "Zagreb",
      "89": "Sarajevo",
      "90": "Valletta",
      "91": "Cairo",
      "92": "Doha",
      "93": "Dakar",
      "94": "Banjul",
      "95": "Ulaanbaatar",
      "96": "Ljubljana",
      "97": "Luxembourg City",
      "98": "Nassau",
      "99": "Reykjavik",
      "100": "Antananarivo"
}
,"8":
{
  "1": "The Shawshank Redemption",
  "2": "The Godfather",
  "3": "Pulp Fiction",
  "4": "Fight Club",
  "5": "The Dark Knight",
  "6": "The Matrix",
  "7": "Inception",
  "8": "Goodfellas",
  "9": "Schindler's List",
  "10": "Forrest Gump",
  "11": "Interstellar",
  "12": "The Silence of the Lambs",
  "13": "The Lord of the Rings: The Fellowship of the Ring",
  "14": "Casablanca",
  "15": "The Avengers",
  "16": "Se7en",
  "17": "The Usual Suspects",
  "18": "The Departed",
  "19": "Gladiator",
  "20": "The Lion King",
  "21": "The Prestige",
  "22": "Django Unchained",
  "23": "Gone with the Wind",
  "24": "The Shawshank Redemption",
  "25": "The Godfather: Part II",
  "26": "Inglourious Basterds",
  "27": "Drive",
  "28": "The Social Network",
  "29": "A Clockwork Orange",
  "30": "Eternal Sunshine of the Spotless Mind",
  "31": "Mad Max: Fury Road",
  "32": "The Big Lebowski",
  "33": "The Grand Budapest Hotel",
  "34": "The Shining",
  "35": "Blade Runner",
  "36": "Toy Story",
  "37": "Memento",
  "38": "The Green Mile",
  "39": "WALL-E",
  "40": "Requiem for a Dream",
  "41": "Jurassic Park",
  "42": "Saving Private Ryan",
  "43": "Apocalypse Now",
  "44": "Her",
  "45": "Crouching Tiger, Hidden Dragon",
  "46": "Oldboy",
  "47": "American History X",
  "48": "The Departed",
  "49": "The Dark Knight Rises",
  "50": "Raging Bull",
  "51": "Up",
  "52": "The Revenant",
  "53": "Fight Club",
  "54": "Jaws",
  "55": "Good Will Hunting",
  "56": "There Will Be Blood",
  "57": "Scarface",
  "58": "Gone Girl",
  "59": "The Matrix",
  "60": "A Beautiful Mind",
  "61": "Gravity",
  "62": "The Sixth Sense",
  "63": "A Nightmare on Elm Street",
  "64": "Black Swan",
  "65": "Die Hard",
  "66": "The Exorcist",
  "67": "No Country for Old Men",
  "68": "La La Land",
  "69": "The Wolf of Wall Street",
  "70": "Trainspotting",
  "71": "Boyhood",
  "72": "Chinatown",
  "73": "Joker",
  "74": "The Lord of the Rings: The Return of the King",
  "75": "Scarface",
  "76": "Avatar",
  "77": "Inception",
  "78": "E.T. the Extra-Terrestrial",
  "79": "Full Metal Jacket",
  "80": "Seven Samurai",
  "81": "Amelie",
  "82": "A Star is Born",
  "83": "Into the Wild",
  "84": "Inglourious Basterds",
  "85": "The Flash",
  "86": "Snatch",
  "87": "Reservoir Dogs",
  "88": "Catch Me If You Can",
  "89": "Drive",
  "90": "Singin' in the Rain",
  "91": "The Usual Suspects",
  "92": "Shutter Island",
  "93": "Rain Man",
  "94": "The Dark Knight",
  "95": "Rocky",
  "96": "Citizen Kane",
  "97": "Gran Torino",
  "98": "City of God",
  "99": "Whiplash",
  "100": "Memento"
},
"9":
{
  "1": "1984",
  "2": "Moby Dick",
  "3": "To Kill a Mockingbird",
  "4": "Pride and Prejudice",
  "5": "The Catcher in the Rye",
  "6": "The Great Gatsby",
  "7": "Brave New World",
  "8": "Anna Karenina",
  "9": "The Lord of the Rings",
  "10": "The Hobbit",
  "11": "The Odyssey",
  "12": "Frankenstein",
  "13": "Crime and Punishment",
  "14": "Wuthering Heights",
  "15": "The Adventures of Sherlock Holmes",
  "16": "To the Lighthouse",
  "17": "The Picture of Dorian Gray",
  "18": "Gone with the Wind",
  "19": "Alice's Adventures in Wonderland",
  "20": "Fahrenheit 451",
  "21": "Don Quixote",
  "22": "The Hound of the Baskervilles",
  "23": "Jane Eyre",
  "24": "One Hundred Years of Solitude",
  "25": "The Wind-up Bird Chronicle",
  "26": "The Da Vinci Code",
  "27": "Moby Dick",
  "28": "1984",
  "29": "The Alchemist",
  "30": "Walden",
  "31": "Pride and Prejudice",
  "32": "Invisible Man",
  "33": "Great Expectations",
  "34": "The Color Purple",
  "35": "The Chronicles of Narnia",
  "36": "The Secret History",
  "37": "The Shining",
  "38": "The Adventures of Tom Sawyer",
  "39": "Of Mice and Men",
  "40": "Catch-22",
  "41": "Lord of the Flies",
  "42": "Ulysses",
  "43": "Gulliver's Travels",
  "44": "The Grapes of Wrath",
  "45": "The Book Thief",
  "46": "Beloved",
  "47": "The Metamorphosis",
  "48": "The Sun Also Rises",
  "49": "The Scarlet Letter",
  "50": "A Game of Thrones",
  "51": "The Old Man and the Sea",
  "52": "Slaughterhouse-Five",
  "53":"Meditations",
  "54":"A Tale of Two Cities",
  "55":"War and Peace",
  "56":"The Awakening",
  "57":"The Count of Monte Cristo",
  "58":"Life of Pi",
  "59":"Les Misérables",
  "60":"The Grapes of Wrath",
  "61":"The Great Gatsby",
  "62":"The Da Vinci Code",
  "63":"Crime and Punishment",
  "64":"Don Quixote",
  "65":"Fahrenheit 451",
  "66":"The Lord of the Rings",
  "67":"Moby Dick",
  "68":"One Hundred Years of Solitude",
  "69":"The Adventures of Sherlock Holmes",
  "70":"Jane Eyre",
  "71":"Wuthering Heights",
  "72":"Breakfast of Champions",
  "73":"The Bell Jar",
  "74":"1984",
  "75":"Atlas Shrugged",
  "76":"Brave New World",
  "77":"Slaughterhouse-Five",
  "78":"The Hobbit",
  "79":"Pride and Prejudice",
  "80":"A Clockwork Orange",
  "81":"Nineteen Eighty Four",
  "82":"Treasure Island",
  "83":"The Diary of a Young Girl",
  "84":"Little Women",
  "85":"Heart of Darkness",
  "86":"The Brothers Karamazov",
  "87":"Fear and Loathing in Las Vegas",
  "88":"Catch Me If You Can",
  "89":"Middlemarch",
  "90":"Eleanor Oliphant is Completely Fine",
  "91":"The Trials of Apollo",
  "92":"Becoming",
  "93":"Educated",
  "94":"The Silent Patient",
  "95":"The Tattooist of Auschwitz",
  "96":"Dear Edward",
  "97":"The Guardians",
  "98":"The Dutch House",
  "99":"The Giver of Stars",
  "100":"The Testaments"
},
"10":
{
  "1": "Apple Inc.",
  "2": "Microsoft Corporation",
  "3": "Amazon.com, Inc.",
  "4": "Alphabet Inc.",
  "5": "Facebook, Inc.",
  "6": "Tesla, Inc.",
  "7": "Netflix, Inc.",
  "8": "Walmart Inc.",
  "9": "Johnson & Johnson",
  "10": "Procter & Gamble Co.",
  "11": "The Coca-Cola Company",
  "12": "Pfizer Inc.",
  "13": "Intel Corporation",
  "14": "IBM",
  "15": "General Electric Company",
  "16": "Boeing Company",
  "17": "Toyota Motor Corporation",
  "18": "Nike, Inc.",
  "19": "McDonald's Corporation",
  "20": "Starbucks Corporation",
  "21": "Visa Inc.",
  "22": "Mastercard Incorporated",
  "23": "American Express Company",
  "24": "JPMorgan Chase & Co.",
  "25": "Bank of America Corporation",
  "26": "Goldman Sachs Group, Inc.",
  "27": "Walt Disney Company",
  "28": "AT&T Inc.",
  "29": "Verizon Communications Inc.",
  "30": "Comcast Corporation",
  "31": "Uber Technologies, Inc.",
  "32": "Lyft, Inc.",
  "33": "Airbnb, Inc.",
  "34": "Snap Inc.",
  "35": "Twitter, Inc.",
  "36": "Salesforce.com, Inc.",
  "37": "Oracle Corporation",
  "38": "Adobe Inc.",
  "39": "Cisco Systems, Inc.",
  "40": "HP Inc.",
  "41": "Dell Technologies Inc.",
  "42": "Sony Corporation",
  "43": "Samsung Electronics Co., Ltd.",
  "44": "LG Electronics Inc.",
  "45": "General Motors Company",
  "46": "Ford Motor Company",
  "47": "Honda Motor Co., Ltd.",
  "48": "Volkswagen AG",
  "49": "BMW AG",
  "50": "Mercedes-Benz",
  "51": "L'Oréal S.A.",
  "52": "The Estée Lauder Companies Inc.",
  "53": "Unilever",
  "54": "Nestlé S.A.",
  "55": "PepsiCo, Inc.",
  "56": "The Walt Disney Company",
  "57": "Time Warner Inc.",
  "58": "21st Century Fox",
  "59": "CBS Corporation",
  "60": "Sony Pictures Entertainment Inc.",
  "61": "Warner Bros. Entertainment Inc.",
  "62": "Universal Pictures",
  "63": "Paramount Pictures",
  "64": "Netflix, Inc.",
  "65": "HBO",
  "66": "Amazon Studios",
  "67": "Electronic Arts Inc.",
  "68": "Activision Blizzard, Inc.",
  "69": "Take-Two Interactive Software, Inc.",
  "70": "Ubisoft Entertainment SA",
  "71": "Square Enix Holdings Co., Ltd.",
  "72": "Nintendo Co., Ltd.",
  "73": "Sony Interactive Entertainment LLC",
  "74": "Microsoft Studios",
  "75": "Google LLC",
  "76": "Alibaba Group Holding Limited",
  "77": "Tencent Holdings Limited",
  "78": "Baidu, Inc.",
  "79": "JD.com, Inc.",
  "80": "PayPal Holdings, Inc.",
  "81": "Square, Inc.",
  "82": "Stripe, Inc.",
  "83": "Coinbase Global, Inc.",
  "84": "Robinhood Markets, Inc.",
  "85": "Zoom Video Communications, Inc.",
  "86": "Slack Technologies, Inc.",
  "87": "Dropbox, Inc.",
  "88": "Spotify Technology S.A.",
  "89": "TikTok",
  "90": "Pinterest, Inc.",
  "91": "Snap Inc.",
  "92": "Reddit, Inc.",
  "93": "Etsy, Inc.",
  "94": "Match Group, Inc.",
  "95": "Tripadvisor, Inc.",
  "96": "Expedia Group, Inc.",
  "97": "Booking Holdings Inc.",
  "98": "Uber Technologies, Inc.",
  "99": "Lyft, Inc.",
  "100": "Airbnb, Inc."
},
"11":
{
  "1": "Harvard University",
  "2": "Stanford University",
  "3": "Massachusetts Institute of Technology",
  "4": "California Institute of Technology",
  "5": "University of Oxford",
  "6": "University of Cambridge",
  "7": "Princeton University",
  "8": "Yale University",
  "9": "Columbia University",
  "10": "University of Chicago",
  "11": "University of California, Berkeley",
  "12": "University of California, Los Angeles",
  "13": "University of Michigan",
  "14": "University of Pennsylvania",
  "15": "Cornell University",
  "16": "Johns Hopkins University",
  "17": "Northwestern University",
  "18": "Duke University",
  "19": "University of California, San Diego",
  "20": "University of Texas at Austin",
  "21": "University of Washington",
  "22": "University of Wisconsin-Madison",
  "23": "University of Illinois at Urbana-Champaign",
  "24": "University of Toronto",
  "25": "University of British Columbia",
  "26": "McGill University",
  "27": "University of Melbourne",
  "28": "University of Sydney",
  "29": "University of Tokyo",
  "30": "Kyoto University",
  "31": "Peking University",
  "32": "Tsinghua University",
  "33": "Seoul National University",
  "34": "National University of Singapore",
  "35": "University of Cape Town",
  "36": "University of São Paulo",
  "37": "University of Buenos Aires",
  "38": "University of Cape Town",
  "39": "University of Nairobi",
  "40": "University of Mumbai",
  "41": "University of Delhi",
  "42": "University of Sydney",
  "43": "University of Melbourne",
  "44": "University of Auckland",
  "45": "University of Toronto",
  "46": "University of British Columbia",
  "47": "University of Alberta",
  "48": "University of Waterloo",
  "49": "University of Paris",
  "50": "University of Cambridge",
  "51": "University of Oxford",
  "52": "University of Edinburgh",
  "53": "University of Glasgow",
  "54": "University of Manchester",
  "55": "University of Bristol",
  "56": "University of Birmingham",
  "57": "University of Leeds",
  "58": "University of Sheffield",
  "59": "University of Southampton",
  "60": "University of Warwick",
  "61": "University of London",
  "62": "University of California, Berkeley",
  "63": "University of California, Los Angeles",
  "64": "University of California, San Diego",
  "65": "University of California, Santa Barbara",
  "66": "University of California, Irvine",
  "67": "University of California, Davis",
  "68": "University of California, Riverside",
  "69": "University of California, Santa Cruz",
  "70": "University of Southern California",
  "71": "University of Michigan",
  "72": "Michigan State University",
  "73": "Wayne State University",
  "74": "University of Chicago",
  "75": "Northwestern University",
  "76": "University of Illinois at Urbana-Champaign",
  "77": "University of Wisconsin-Madison",
  "78": "University of Minnesota",
  "79": "University of Texas at Austin",
  "80": "Texas A&M University",
  "81": "Rice University",
  "82": "University of Washington",
  "83": "University of Oregon",
  "84": "University of Colorado Boulder",
  "85": "University of Arizona",
  "86": "University of Utah",
  "87": "University of British Columbia",
  "88": "University of Toronto",
  "89": "McGill University",
  "90": "University of Alberta",
  "91": "University of Waterloo",
  "92": "University of Sydney",
  "93": "University of Melbourne",
  "94": "University of Queensland",
  "95": "University of New South Wales",
  "96": "University of Auckland",
  "97": "University of Otago",
  "98": "University of Tokyo",
  "99": "Kyoto University",
  "100": "Osaka University"
},
"12":
{
  "1": "Football",
  "2": "Basketball",
  "3": "Baseball",
  "4": "Soccer",
  "5": "Tennis",
  "6": "Golf",
  "7": "Cricket",
  "8": "Rugby",
  "9": "Hockey",
  "10": "Volleyball",
  "11": "Swimming",
  "12": "Athletics",
  "13": "Boxing",
  "14": "Martial Arts",
  "15": "Cycling",
  "16": "Wrestling",
  "17": "Gymnastics",
  "18": "Ice Hockey",
  "19": "Table Tennis",
  "20": "Badminton",
  "21": "Weightlifting",
  "22": "Snowboarding",
  "23": "Skiing",
  "24": "Surfing",
  "25": "Diving",
  "26": "Rowing",
  "27": "Sailing",
  "28": "Fencing",
  "29": "Archery",
  "30": "Shooting",
  "31": "Triathlon",
  "32": "Canoeing",
  "33": "Kayaking",
  "34": "Polo",
  "35": "Handball",
  "36": "Softball",
  "37": "Lacrosse",
  "38": "Ultimate Frisbee",
  "39": "Skateboarding",
  "40": "Bowling",
  "41": "Billiards",
  "42": "Rugby Sevens",
  "43": "Beach Volleyball",
  "44": "Synchronized Swimming",
  "45": "Water Polo",
  "46": "Figure Skating",
  "47": "Speed Skating",
  "48": "Short Track Speed Skating",
  "49": "Bobsleigh",
  "50": "Skeleton",
  "51": "Curling",
  "52": "Biathlon",
  "53": "Cross-Country Skiing",
  "54": "Figure Skating",
  "55": "Marathon",
  "56": "Half Marathon",
  "57": "Ironman Triathlon",
  "58": "High Jump",
  "59": "Long Jump",
  "60": "Triple Jump",
  "61": "Pole Vault",
  "62": "Shot Put",
  "63": "Discus Throw",
  "64": "Hammer Throw",
  "65": "Javelin Throw",
  "66": "Decathlon",
  "67": "Heptathlon",
  "68": "Mountain Biking",
  "69": "Road Cycling",
  "70": "BMX Racing",
  "71": "BMX Freestyle",
  "72": "Taekwondo",
  "73": "Karate",
  "74": "Judo",
  "75": "Wushu",
  "76": "Muay Thai",
  "77": "Kickboxing",
  "78": "Sumo Wrestling",
  "79": "WWE Wrestling",
  "80": "Synchronized Diving",
  "81": "Platform Diving",
  "82": "Open Water Swimming",
  "83": "Water Skiing",
  "84": "Wakeboarding",
  "85": "Canoe Slalom",
  "86": "Canoe Sprint",
  "87": "Sailing",
  "88": "Pentathlon",
  "89": "Modern Pentathlon",
  "90": "Rhythmic Gymnastics",
  "91": "Trampoline Gymnastics",
  "92": "Artistic Gymnastics",
  "93": "Beach Soccer",
  "94": "Indoor Soccer",
  "95": "Rugby League",
  "96": "Rugby Union",
  "97": "Ice Skating",
  "98": "Snow Skiing",
  "99": "Snowboarding",
  "100": "Surfing"
},
"13":
{
  "1": "Eiffel Tower",
  "2": "Statue of Liberty",
  "3": "Great Wall of China",
  "4": "Taj Mahal",
  "5": "Machu Picchu",
  "6": "Pyramids of Giza",
  "7": "Colosseum",
  "8": "Sagrada Familia",
  "9": "Acropolis of Athens",
  "10": "Angkor Wat",
  "11": "Christ the Redeemer",
  "12": "Sydney Opera House",
  "13": "Grand Canyon",
  "14": "Niagara Falls",
  "15": "Mount Everest",
  "16": "Serengeti National Park",
  "17": "Great Barrier Reef",
  "18": "Petra",
  "19": "Machu Picchu",
  "20": "Chichen Itza",
  "21": "The Louvre",
  "22": "Golden Gate Bridge",
  "23": "Museum of Modern Art",
  "24": "Museum of Natural History",
  "25": "Central Park",
  "26": "Times Square",
  "27": "The Vatican",
  "28": "The Alhambra",
  "29": "The Parthenon",
  "30": "The British Museum",
  "31": "The Tower of London",
  "32": "The Sydney Harbour Bridge",
  "33": "The Great Sphinx of Giza",
  "34": "The Sistine Chapel",
  "35": "The Palace Museum (Forbidden City)",
  "36": "The Hermitage Museum",
  "37": "The Dubai Mall",
  "38": "The Pyramids of Teotihuacan",
  "39": "The Amazon Rainforest",
  "40": "The Galapagos Islands",
  "41": "The Serengeti National Park",
  "42": "The Victoria Falls",
  "43": "The Iguazu Falls",
  "44": "The Amazon River",
  "45": "The Sahara Desert",
  "46": "The Great Barrier Reef",
  "47": "The Ayers Rock (Uluru)",
  "48": "The Niagara Falls",
  "49": "The Rocky Mountains",
  "50": "The Grand Canyon",
  "51": "The Hollywood Walk of Fame",
  "52": "The Las Vegas Strip",
  "53": "The Golden Gate Bridge",
  "54": "The Walt Disney World Resort",
  "55": "The Universal Studios Hollywood",
  "56": "The Times Square",
  "57": "The Central Park",
  "58": "The Statue of Liberty",
  "59": "The Empire State Building",
  "60": "The White House",
  "61": "The Smithsonian Institution",
  "62": "The National Mall",
  "63": "The Lincoln Memorial",
  "64": "The Mount Rushmore National Memorial",
  "65": "The Kennedy Space Center",
  "66": "The Bourbon Street",
  "67": "The French Quarter",
  "68": "The Statue of Liberty National Monument",
  "69": "The Golden Gate Park",
  "70": "The Fisherman's Wharf",
  "71": "The Hollywood Sign",
  "72": "The Griffith Observatory",
  "73": "The Getty Center",
  "74": "The San Diego Zoo",
  "75": "The Alcatraz Island",
  "76": "The Pike Place Market",
  "77": "The Space Needle",
  "78": "The Mount Rainier National Park",
  "79": "The Glacier National Park",
  "80": "The Yellowstone National Park",
  "81": "The Grand Teton National Park",
  "82": "The Rocky Mountain National Park",
  "83": "The Great Sand Dunes National Park",
  "84": "The Mesa Verde National Park",
  "85": "The Everglades National Park",
  "86": "The Biscayne National Park",
  "87": "The Dry Tortugas National Park",
  "88": "The Carlsbad Caverns National Park",
  "89": "The Mount Rushmore National Memorial",
  "90": "The Badlands National Park",
  "91": "The Zion National Park",
  "92": "The Bryce Canyon National Park",
  "93": "The Arches National Park",
  "94": "The Canyonlands National Park",
  "95": "The Capitol Reef National Park",
  "96": "The Great Smoky Mountains National Park",
  "97": "The Shenandoah National Park",
  "98": "The Mammoth Cave National Park",
  "99": "The Everglades National Park",
  "100": "The Hawaii Volcanoes National Park"
},
"14":
{
  "1": "Smartphone",
  "2": "Laptop",
  "3": "Tablet",
  "4": "Smartwatch",
  "5": "Desktop Computer",
  "6": "Smart TV",
  "7": "Gaming Console",
  "8": "Bluetooth Speaker",
  "9": "Headphones",
  "10": "Fitness Tracker",
  "11": "Digital Camera",
  "12": "Printer",
  "13": "Router",
  "14": "External Hard Drive",
  "15": "Smart Home Hub",
  "16": "E-reader",
  "17": "Portable Charger",
  "18": "Virtual Reality Headset",
  "19": "Drone",
  "20": "Smart Thermostat",
  "21": "Smart Lock",
  "22": "Wireless Earbuds",
  "23": "Car GPS",
  "24": "Smart Scale",
  "25": "Wireless Mouse",
  "26": "Gamepad",
  "27": "Bluetooth Keyboard",
  "28": "Smart Plug",
  "29": "Action Camera",
  "30": "Wireless Router",
  "31": "Bluetooth Earphones",
  "32": "Smart Mirror",
  "33": "Robot Vacuum",
  "34": "Bluetooth Headset",
  "35": "Projector",
  "36": "Smart Doorbell",
  "37": "Streaming Stick",
  "38": "Wireless Printer",
  "39": "Bluetooth Mouse",
  "40": "Smart Speaker",
  "41": "Wireless Keyboard",
  "42": "Fitness Smartwatch",
  "43": "Car Dash Cam",
  "44": "Wireless Headphones",
  "45": "Smart Oven",
  "46": "Smart Fridge",
  "47": "Bluetooth Tracker",
  "48": "Smart Light Bulb",
  "49": "Smart Vacuum Cleaner",
  "50": "Wireless Security Camera",
  "51": "Portable Bluetooth Speaker",
  "52": "Smart Garage Door Opener",
  "53": "Wireless Gaming Mouse",
  "54": "Bluetooth Game Controller",
  "55": "Smart Coffee Maker",
  "56": "Smart Water Bottle",
  "57": "Wireless Charging Pad",
  "58": "Bluetooth Car Kit",
  "59": "Smart Air Purifier",
  "60": "Wireless Webcam",
  "61": "Smart Plant Pot",
  "62": "Bluetooth FM Transmitter",
  "63": "Smart Pet Feeder",
  "64": "Wireless Surround Sound System",
  "65": "Bluetooth Noise Cancelling Headphones",
  "66": "Smart Window Blinds",
  "67": "Wireless HDMI Transmitter",
  "68": "Smart Ceiling Fan",
  "69": "Bluetooth Shower Speaker",
  "70": "Smart Lawn Mower",
  "71": "Wireless Gaming Headset",
  "72": "Bluetooth Smart Lock",
  "73": "Smart Water Leak Detector",
  "74": "Wireless Karaoke Microphone",
  "75": "Smart Bike Lock",
  "76": "Bluetooth Bike Speaker",
  "77": "Smart Clothes Hanger",
  "78": "Wireless Bike Computer",
  "79": "Bluetooth Meat Thermometer",
  "80": "Smart Umbrella",
  "81": "Wireless Baby Monitor",
  "82": "Bluetooth Sleep Mask",
  "83": "Smart Plant Sensor",
  "84": "Wireless HDMI Adapter",
  "85": "Bluetooth BBQ Grill Thermometer",
  "86": "Smart Wine Bottle Opener",
  "87": "Wireless Charging Mouse Pad",
  "88": "Bluetooth Tracking Tag",
  "89": "Smart Egg Tray",
  "90": "Wireless Presentation Remote",
  "91": "Bluetooth Light Switch",
  "92": "Smart Watering System",
  "93": "Wireless Barcode Scanner",
  "94": "Bluetooth Wine Thermometer",
  "95": "Smart Cutlery Set",
  "96": "Wireless Weather Station",
  "97": "Bluetooth Sleep Tracker",
  "98": "Smart Compost Bin",
  "99": "Wireless Bike Lock",
  "100": "Bluetooth Coffee Mug"
},
"15":
{
  "1": "dog",
  "2": "cat",
  "3": "elephant",
  "4": "lion",
  "5": "tiger",
  "6": "giraffe",
  "7": "zebra",
  "8": "monkey",
  "9": "panda",
  "10": "koala",
  "11": "kangaroo",
  "12": "hippopotamus",
  "13": "rhinoceros",
  "14": "crocodile",
  "15": "alligator",
  "16": "snake",
  "17": "turtle",
  "18": "frog",
  "19": "toad",
  "20": "lizard",
  "21": "chameleon",
  "22": "parrot",
  "23": "eagle",
  "24": "hawk",
  "25": "owl",
  "26": "penguin",
  "27": "ostrich",
  "28": "flamingo",
  "29": "peacock",
  "30": "swan",
  "31": "duck",
  "32": "goose",
  "33": "pigeon",
  "34": "sparrow",
  "35": "seagull",
  "36": "dolphin",
  "37": "whale",
  "38": "shark",
  "39": "octopus",
  "40": "jellyfish",
  "41": "starfish",
  "42": "crab",
  "43": "lobster",
  "44": "fish",
  "45": "clownfish",
  "46": "goldfish",
  "47": "swordfish",
  "48": "butterfly",
  "49": "bee",
  "50": "ant",
  "51": "ladybug",
  "52": "spider",
  "53": "scorpion",
  "54": "snail",
  "55": "caterpillar",
  "56": "centipede",
  "57": "beetle",
  "58": "grasshopper",
  "59": "cricket",
  "60": "cow",
  "61": "horse",
  "62": "sheep",
  "63": "goat",
  "64": "pig",
  "65": "chicken",
  "66": "rooster",
  "67": "duckling",
  "68": "turkey",
  "69": "rabbit",
  "70": "hamster",
  "71": "guinea pig",
  "72": "mouse",
  "73": "rat",
  "74": "squirrel",
  "75": "polar bear",
  "76": "grizzly bear",
  "77": "panda bear",
  "78": "koala bear",
  "79": "gorilla",
  "80": "chimpanzee",
  "81": "orangutan",
  "82": "sloth",
  "83": "hedgehog",
  "84": "armadillo",
  "85": "kangaroo rat",
  "86": "platypus",
  "87": "wombat",
  "88": "anteater",
  "89": "beaver",
  "90": "raccoon",
  "91": "fox",
  "92": "wolf",
  "93": "coyote",
  "94": "deer",
  "95": "elk",
  "96": "moose",
  "97": "gazelle",
  "98": "zebu",
  "99": "buffalo",
  "100": "rhinoceros"
}
}